"""init tables single role

Revision ID: 8969262c9d0c
Revises: 
Create Date: 2026-09-24 18:59:20.279149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8969262c9d0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_resource',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('device_name', sa.String(length=128), nullable=False, comment='设备名称'),
    sa.Column('device_type', sa.String(length=64), nullable=True, comment='设备类型'),
    sa.Column('device_status', sa.Integer(), nullable=False, comment='设备状态：1完好，2损坏，3缺失配件'),
    sa.Column('total_count', sa.Integer(), nullable=False, comment='总数量'),
    sa.Column('available_count', sa.Integer(), nullable=False, comment='可用数量'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('space_resource',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('space_name', sa.String(length=128), nullable=False, comment='空间名称'),
    sa.Column('space_type', sa.Integer(), nullable=False, comment='空间类型：1会议室 2展厅 3多功能厅 4户外场地'),
    sa.Column('capacity', sa.Integer(), nullable=False, comment='容纳人数'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='位置'),
    sa.Column('budget', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='预算'),
    sa.Column('open_start_time', sa.Time(), nullable=True, comment='开放起始时间'),
    sa.Column('open_end_time', sa.Time(), nullable=True, comment='开放结束时间'),
    sa.Column('status', sa.Integer(), nullable=False, comment='可用状态：1可用 0停用'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_permission',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('permission_name', sa.String(length=64), nullable=False, comment='权限名称'),
    sa.Column('permission_code', sa.String(length=128), nullable=False, comment='权限编码，如 user:add'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父权限ID，树形结构'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_code')
    )
    op.create_table('sys_role',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('role_name', sa.String(length=64), nullable=False, comment='角色名称'),
    sa.Column('permissions', sa.JSON(), nullable=True, comment='权限集合，JSON数组'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='登录名'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('role_id', sa.BigInteger(), nullable=True, comment='角色ID'),
    sa.Column('avatar', sa.String(length=512), nullable=True, comment='头像地址'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态：1正常，0禁用'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('inspect_record',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('space_id', sa.BigInteger(), nullable=True, comment='巡检关联的空间ID'),
    sa.Column('image_url', sa.String(length=512), nullable=False, comment='巡检图片地址'),
    sa.Column('ai_result', sa.JSON(), nullable=True, comment='AI识别结果'),
    sa.Column('inspector_id', sa.BigInteger(), nullable=False, comment='巡检人ID'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['inspector_id'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['space_resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserve_order',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='预约人ID'),
    sa.Column('space_id', sa.BigInteger(), nullable=False, comment='空间ID'),
    sa.Column('device_ids', sa.JSON(), nullable=True, comment='设备ID列表'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=False, comment='结束时间'),
    sa.Column('order_status', sa.Integer(), nullable=False, comment='订单状态：1待确认，2已确认，3已取消，4已完成'),
    sa.Column('agent_request', sa.String(length=1024), nullable=True, comment='用户原始需求'),
    sa.Column('agent_trace', sa.JSON(), nullable=True, comment='AI思考过程追踪'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['space_id'], ['space_resource.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notify_message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('receiver_id', sa.BigInteger(), nullable=False, comment='接收人ID'),
    sa.Column('notify_type', sa.Integer(), nullable=False, comment='通知类型：1预约提醒 2变更致歉 3故障告警'),
    sa.Column('order_id', sa.BigInteger(), nullable=True, comment='关联订单ID'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='通知标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='通知内容'),
    sa.Column('is_read', sa.Integer(), nullable=False, comment='0未读，1已读'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['order_id'], ['reserve_order.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repair_ticket',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('inspect_id', sa.BigInteger(), nullable=True, comment='关联巡检记录ID'),
    sa.Column('device_id', sa.BigInteger(), nullable=True, comment='关联设备ID'),
    sa.Column('space_id', sa.BigInteger(), nullable=True, comment='关联空间ID'),
    sa.Column('ticket_status', sa.Integer(), nullable=False, comment='工单状态：1待处理，2处理中，3已完成'),
    sa.Column('handler_id', sa.BigInteger(), nullable=True, comment='处理人ID'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['device_id'], ['device_resource.id'], ),
    sa.ForeignKeyConstraint(['handler_id'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['inspect_id'], ['inspect_record.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['space_resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repair_ticket')
    op.drop_table('notify_message')
    op.drop_table('reserve_order')
    op.drop_table('inspect_record')
    op.drop_table('sys_user')
    op.drop_table('sys_role')
    op.drop_table('sys_permission')
    op.drop_table('space_resource')
    op.drop_table('device_resource')
    # ### end Alembic commands ###
